### ISSUE TITLE
Error enlace hito 3

### ISSUE THREAD

**Issue by acasadoquijada** [JJ/CC16-17#139]
En el fichero de la [semana 9](https://github.com/JJ/CC16-17/blob/master/sesiones/9-semana.md) el enlace al Hito 3 está mal, hay que quitar el .md del enlace

**Comment by JJ** [comment]
Pull request, ¿no?

**Comment by acasadoquijada** [comment]
[Hecho](https://github.com/JJ/CC16-17/pull/140)
